version: '3.2'
services:
  acme-srv:
    build:
      context: ../../.
      dockerfile: examples/Docker/$WEBSERVER/$CONTEXT/Dockerfile
    image: acme2certifier/$CONTEXT
    volumes:
      - type: bind
        source: ./data
        target: /var/www/acme2certifier/volume/
        read_only: false
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    ports:
      - "80:80"
      - "443:443"
    restart: always
    network_mode: host

networks:
  default:
    external:
      name: acme
