---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-depl
spec:
  selector:
    matchLabels:
      app: webserver-app
  template:
    metadata:
      labels:
        app: webserver-app
    spec:
      containers:
        - name: webserver-app
          image: nginx:1.8
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
spec:
  selector:
    app: webserver-app
  ports:
    - name: webserver-app
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-routes
  annotations:
    cert-manager.io/cluster-issuer: "acme2certifier"
spec:
  tls:
    - hosts:
        - www.bar.local
      secretName: tls-secret
  rules:
    - host: www.bar.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webserver-svc
                port:
                  number: 80
  ingressClassName: public

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme2certifier
spec:
  acme:
    server: http://ACME_SRV/directory
    email: grindsa@bar.local
    privateKeySecretRef:
      name: a2c
    solvers:
      - http01:
          ingress:
            ingressTemplate:
              metadata:
                annotations:
                  ingressClassName: public
