---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-acme
---
apiVersion: v1
kind: Pod
metadata:
  name: acme2certifier
  namespace: cert-manager-acme
  labels:
    app: a2c
spec:
  hostname: acme-srv
  containers:
    - name: acme2certifier
      image: grindsa/acme2certifier:devel
      imagePullPolicy: Never
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /var/www/acme2certifier/volume/
          name: a2c-volume
  volumes:
    - name: a2c-volume
      hostPath:
        path: /home/runner/work/acme2certifier/acme2certifier/data
        type: Directory
